class TestForgetPassword:
    def test_forget_password_successful(self) -> None: ...

    def test_forget_password_user_not_found(self) -> None: ...

    def test_forget_password_invalid_email(self) -> None: ...
