class TestResetPassword:
    def test_reset_password_successful(self) -> None: ...

    def test_reset_password_invalid_password(self) -> None: ...

    def test_reset_password_user_not_auth(self) -> None: ...
