name: Code Quality Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
        
      - name: List files
        run: ls -la

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: isort check
        run: isort --check-only --profile black src tests cli.py

      - name: black check
        run: black --check src tests cli.py
