name: Pre Merge Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-merge-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: isort check
        run: isort --check-only --profile black src tests cli.py

      - name: black check
        run: black --check src tests cli.py

      - name: mypy check
        run: mypy src tests cli.py

      - name: Run tests
        run: pytest tests
      
      - name: Create PR review request
        if : github.event_name == 'pull_request' && github.event.pull_request.user.login != 'jadshaker'
        run: |
          gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          /repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers \
          -f "reviewers[]=jadshaker" \
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
