name: Data Scraping Workflow

on:
  push:
    branches: [Jad/scraping-data]

jobs:
  python-code-cleaning-and-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the scraper
        run: python src/scraper.py
